### ISSUE TITLE
평가기 제작

### ISSUE THREAD

**Issue by ENvironmentSet** [ENvironmentSet/Acropolis#9]
- Step 1: Building Block 정의
  - [x] Abstract Machine 정의
  - [x] Runtime Environment 정의
  - [x] Values & Types 정의
- Step 2: 함수 구현
- Step 3: 표현식 구현
  - [x] 리터럴
  - [x] Left-Hand-Side (식별자 참조, this, 프로퍼티 접근자)
  - [ ] 업데이트 연산자 (Inc/Dec both post and pre)
  - [x] 함수 호출
  - [ ] new 연산자
  - [ ] 일반 단항 연산자(delete/void/typeof)
  - [x] 산술 연산자
  - [ ] 비트 연산자
  - [ ] 관계 연산자
  - [ ] 논리 연산자
  - [x] 대입 연산자
  - [ ] 컴마 연산자
  - [x] Groupping
- Step 4: 구문 구현
  - [x] 빈 구문
  - [x] 표현식 구문
  - [x] 변수 구문
  - [x] If문
  - [ ] 반복문
  - [ ] 흐름 제어문(break/continue/return)
  - [ ] with문
  - [x] 블록
- Step 5: 전역 스코프 구현
  - [ ] 전역 객체
  - [ ] 전역 레벨 코드 해석
- Step 6: 표준 라이브러리 구현
